# Generated by Django 5.1.8 on 2025-05-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="是否为免费页面"),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="required_points",
            field=models.PositiveIntegerField(default=0, verbose_name="所需积分"),
        ),
    ]
