# Generated by Django 5.1.15 on 2026-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="likes",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
    ]
