
services:
  db:
    image: postgres:17.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cheeseoo
      POSTGRES_USER: yangfan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: a_core.settings
      POSTGRES_DB: cheeseoo
      POSTGRES_USER: yangfan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db
      - cache
