# Generated by Django 5.1.15 on 2026-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_agent", "0003_reading_list_and_embeddings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, default="New chat", max_length=120),
        ),
    ]
