# Generated by Django 5.1.8 on 2025-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
