# Generated by Django 5.1.8 on 2025-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0002_profile_is_subscribed_profile_subscription_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
