# Generated by Django 5.1.8 on 2025-05-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0003_profile_subscription_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="积分"),
        ),
    ]
