# Generated by Django 5.1.15 on 2026-08-22 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0005_emailverificationcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowsingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.PositiveIntegerField()),
                ("article_title", models.CharField(max_length=255)),
                ("article_url", models.URLField(max_length=500)),
                ("viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browsing_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览历史",
                "verbose_name_plural": "浏览历史",
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "article_id")},
            },
        ),
    ]
